<!--
 filename: SegaAgent.csproj
-->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>

    <PackageReference
      Include="Microsoft.Extensions.Hosting"
      Version="10.0.10" />

    <PackageReference
      Include="Microsoft.Data.Sqlite"
      Version="10.0.11" />

    <PackageReference
      Include="Microsoft.ML.OnnxRuntime"
      Version="1.29.0" />

    <PackageReference
      Include="NAudio"
      Version="2.3.0" />

    <PackageReference
      Include="System.Speech"
      Version="10.0.10" />

  </ItemGroup>


  <ItemGroup>

    <None Update="Prompt\sega_personality.yaml">
      <CopyToOutputDirectory>
        PreserveNewest
      </CopyToOutputDirectory>
    </None>

    <None Update="Prompt\responder.yaml">
      <CopyToOutputDirectory>
        PreserveNewest
      </CopyToOutputDirectory>
    </None>

    <None Update="Prompt\planner.yaml">
      <CopyToOutputDirectory>
        PreserveNewest
      </CopyToOutputDirectory>
    </None>

  </ItemGroup>


  <ItemGroup>

    <None Include="Piper\**\*">
      <CopyToOutputDirectory>
        PreserveNewest
      </CopyToOutputDirectory>
    </None>

  </ItemGroup>


  <ItemGroup>

    <None Update="Semantic\Models\**\*">
      <CopyToOutputDirectory>
        PreserveNewest
      </CopyToOutputDirectory>
    </None>

  </ItemGroup>

</Project>